apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faas-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # Exemple d’annotations supplémentaires :
    # nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  tls:
  - hosts:
    - faas.local
    secretName: faas-tls-secret
  rules:
  - host: faas.local
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: backend-api-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: faas-frontend-service
            port:
              number: 80